ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

# ADD ./logstash/mysql-connector-java-8.0.27.jar /usr/share/logstash/mysql-connector-java-8.0.27.jar